// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(hypen_engineFFI)
import hypen_engineFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_hypen_engine_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_hypen_engine_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            throw CancellationError()

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * The main Hypen engine interface
 */
public protocol HypenEngineProtocol : AnyObject {
    
    /**
     * Clear the render tree
     */
    func clearTree() 
    
    /**
     * Dispatch an action (queued for polling)
     */
    func dispatchAction(actionName: String, payloadJson: String?) throws 
    
    /**
     * Get pending actions (clears the queue)
     */
    func getPendingActions()  -> [Action]
    
    /**
     * Get pending imports from the last rendered document (clears the queue)
     * Call this after render_source() to discover which components need to be resolved.
     * For each import, use register_component() to provide the resolved component source.
     */
    func getPendingImports()  -> [ImportInfo]
    
    /**
     * Get the current revision number
     */
    func getRevision()  -> UInt64
    
    /**
     * Parse Hypen DSL and return AST as JSON
     */
    func parseToJson(source: String) throws  -> String
    
    /**
     * Register an action handler name
     */
    func registerAction(actionName: String) 
    
    /**
     * Register a component from source
     */
    func registerComponent(component: ComponentDef) throws 
    
    /**
     * Register a primitive element type
     */
    func registerPrimitive(name: String) 
    
    /**
     * Render Hypen DSL source and return patches
     * Supports documents with import statements — call get_pending_imports() after
     * to retrieve imports for resolution by the host SDK.
     */
    func renderSource(source: String) throws  -> [Patch]
    
    /**
     * Set module configuration
     */
    func setModule(config: ModuleConfig) 
    
    /**
     * Update engine state with a JSON patch
     */
    func updateState(stateJson: String) throws  -> [Patch]
    
}

/**
 * The main Hypen engine interface
 */
open class HypenEngine:
    HypenEngineProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_hypen_engine_fn_clone_hypenengine(self.pointer, $0) }
    }
    /**
     * Create a new engine instance
     */
public convenience init()throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeHypenError.lift) {
    uniffi_hypen_engine_fn_constructor_hypenengine_new($0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_hypen_engine_fn_free_hypenengine(pointer, $0) }
    }

    

    
    /**
     * Clear the render tree
     */
open func clearTree() {try! rustCall() {
    uniffi_hypen_engine_fn_method_hypenengine_clear_tree(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Dispatch an action (queued for polling)
     */
open func dispatchAction(actionName: String, payloadJson: String?)throws  {try rustCallWithError(FfiConverterTypeHypenError.lift) {
    uniffi_hypen_engine_fn_method_hypenengine_dispatch_action(self.uniffiClonePointer(),
        FfiConverterString.lower(actionName),
        FfiConverterOptionString.lower(payloadJson),$0
    )
}
}
    
    /**
     * Get pending actions (clears the queue)
     */
open func getPendingActions() -> [Action] {
    return try!  FfiConverterSequenceTypeAction.lift(try! rustCall() {
    uniffi_hypen_engine_fn_method_hypenengine_get_pending_actions(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get pending imports from the last rendered document (clears the queue)
     * Call this after render_source() to discover which components need to be resolved.
     * For each import, use register_component() to provide the resolved component source.
     */
open func getPendingImports() -> [ImportInfo] {
    return try!  FfiConverterSequenceTypeImportInfo.lift(try! rustCall() {
    uniffi_hypen_engine_fn_method_hypenengine_get_pending_imports(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get the current revision number
     */
open func getRevision() -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_hypen_engine_fn_method_hypenengine_get_revision(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Parse Hypen DSL and return AST as JSON
     */
open func parseToJson(source: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeHypenError.lift) {
    uniffi_hypen_engine_fn_method_hypenengine_parse_to_json(self.uniffiClonePointer(),
        FfiConverterString.lower(source),$0
    )
})
}
    
    /**
     * Register an action handler name
     */
open func registerAction(actionName: String) {try! rustCall() {
    uniffi_hypen_engine_fn_method_hypenengine_register_action(self.uniffiClonePointer(),
        FfiConverterString.lower(actionName),$0
    )
}
}
    
    /**
     * Register a component from source
     */
open func registerComponent(component: ComponentDef)throws  {try rustCallWithError(FfiConverterTypeHypenError.lift) {
    uniffi_hypen_engine_fn_method_hypenengine_register_component(self.uniffiClonePointer(),
        FfiConverterTypeComponentDef.lower(component),$0
    )
}
}
    
    /**
     * Register a primitive element type
     */
open func registerPrimitive(name: String) {try! rustCall() {
    uniffi_hypen_engine_fn_method_hypenengine_register_primitive(self.uniffiClonePointer(),
        FfiConverterString.lower(name),$0
    )
}
}
    
    /**
     * Render Hypen DSL source and return patches
     * Supports documents with import statements — call get_pending_imports() after
     * to retrieve imports for resolution by the host SDK.
     */
open func renderSource(source: String)throws  -> [Patch] {
    return try  FfiConverterSequenceTypePatch.lift(try rustCallWithError(FfiConverterTypeHypenError.lift) {
    uniffi_hypen_engine_fn_method_hypenengine_render_source(self.uniffiClonePointer(),
        FfiConverterString.lower(source),$0
    )
})
}
    
    /**
     * Set module configuration
     */
open func setModule(config: ModuleConfig) {try! rustCall() {
    uniffi_hypen_engine_fn_method_hypenengine_set_module(self.uniffiClonePointer(),
        FfiConverterTypeModuleConfig.lower(config),$0
    )
}
}
    
    /**
     * Update engine state with a JSON patch
     */
open func updateState(stateJson: String)throws  -> [Patch] {
    return try  FfiConverterSequenceTypePatch.lift(try rustCallWithError(FfiConverterTypeHypenError.lift) {
    uniffi_hypen_engine_fn_method_hypenengine_update_state(self.uniffiClonePointer(),
        FfiConverterString.lower(stateJson),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHypenEngine: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = HypenEngine

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> HypenEngine {
        return HypenEngine(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: HypenEngine) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HypenEngine {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: HypenEngine, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHypenEngine_lift(_ pointer: UnsafeMutableRawPointer) throws -> HypenEngine {
    return try FfiConverterTypeHypenEngine.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHypenEngine_lower(_ value: HypenEngine) -> UnsafeMutableRawPointer {
    return FfiConverterTypeHypenEngine.lower(value)
}


/**
 * Action dispatched from UI
 */
public struct Action {
    public var name: String
    public var payloadJson: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, payloadJson: String?) {
        self.name = name
        self.payloadJson = payloadJson
    }
}



extension Action: Equatable, Hashable {
    public static func ==(lhs: Action, rhs: Action) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.payloadJson != rhs.payloadJson {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(payloadJson)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAction: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Action {
        return
            try Action(
                name: FfiConverterString.read(from: &buf), 
                payloadJson: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: Action, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterOptionString.write(value.payloadJson, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAction_lift(_ buf: RustBuffer) throws -> Action {
    return try FfiConverterTypeAction.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAction_lower(_ value: Action) -> RustBuffer {
    return FfiConverterTypeAction.lower(value)
}


/**
 * Component definition for registration
 */
public struct ComponentDef {
    public var name: String
    public var source: String
    public var path: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, source: String, path: String) {
        self.name = name
        self.source = source
        self.path = path
    }
}



extension ComponentDef: Equatable, Hashable {
    public static func ==(lhs: ComponentDef, rhs: ComponentDef) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.source != rhs.source {
            return false
        }
        if lhs.path != rhs.path {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(source)
        hasher.combine(path)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeComponentDef: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ComponentDef {
        return
            try ComponentDef(
                name: FfiConverterString.read(from: &buf), 
                source: FfiConverterString.read(from: &buf), 
                path: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ComponentDef, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.source, into: &buf)
        FfiConverterString.write(value.path, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeComponentDef_lift(_ buf: RustBuffer) throws -> ComponentDef {
    return try FfiConverterTypeComponentDef.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeComponentDef_lower(_ value: ComponentDef) -> RustBuffer {
    return FfiConverterTypeComponentDef.lower(value)
}


/**
 * Import information returned to SDK hosts (Kotlin, Swift, etc.)
 */
public struct ImportInfo {
    /**
     * Component names being imported (e.g., ["Button", "Card"])
     */
    public var names: [String]
    /**
     * Source path (e.g., "./components/ui" or "https://cdn.example.com/ui")
     */
    public var sourcePath: String
    /**
     * Source type: "local" or "url"
     */
    public var sourceType: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Component names being imported (e.g., ["Button", "Card"])
         */names: [String], 
        /**
         * Source path (e.g., "./components/ui" or "https://cdn.example.com/ui")
         */sourcePath: String, 
        /**
         * Source type: "local" or "url"
         */sourceType: String) {
        self.names = names
        self.sourcePath = sourcePath
        self.sourceType = sourceType
    }
}



extension ImportInfo: Equatable, Hashable {
    public static func ==(lhs: ImportInfo, rhs: ImportInfo) -> Bool {
        if lhs.names != rhs.names {
            return false
        }
        if lhs.sourcePath != rhs.sourcePath {
            return false
        }
        if lhs.sourceType != rhs.sourceType {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(names)
        hasher.combine(sourcePath)
        hasher.combine(sourceType)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeImportInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ImportInfo {
        return
            try ImportInfo(
                names: FfiConverterSequenceString.read(from: &buf), 
                sourcePath: FfiConverterString.read(from: &buf), 
                sourceType: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ImportInfo, into buf: inout [UInt8]) {
        FfiConverterSequenceString.write(value.names, into: &buf)
        FfiConverterString.write(value.sourcePath, into: &buf)
        FfiConverterString.write(value.sourceType, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImportInfo_lift(_ buf: RustBuffer) throws -> ImportInfo {
    return try FfiConverterTypeImportInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImportInfo_lower(_ value: ImportInfo) -> RustBuffer {
    return FfiConverterTypeImportInfo.lower(value)
}


/**
 * Module configuration
 */
public struct ModuleConfig {
    public var name: String
    public var actions: [String]
    public var stateKeys: [String]
    public var initialStateJson: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, actions: [String], stateKeys: [String], initialStateJson: String) {
        self.name = name
        self.actions = actions
        self.stateKeys = stateKeys
        self.initialStateJson = initialStateJson
    }
}



extension ModuleConfig: Equatable, Hashable {
    public static func ==(lhs: ModuleConfig, rhs: ModuleConfig) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.actions != rhs.actions {
            return false
        }
        if lhs.stateKeys != rhs.stateKeys {
            return false
        }
        if lhs.initialStateJson != rhs.initialStateJson {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(actions)
        hasher.combine(stateKeys)
        hasher.combine(initialStateJson)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeModuleConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ModuleConfig {
        return
            try ModuleConfig(
                name: FfiConverterString.read(from: &buf), 
                actions: FfiConverterSequenceString.read(from: &buf), 
                stateKeys: FfiConverterSequenceString.read(from: &buf), 
                initialStateJson: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ModuleConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterSequenceString.write(value.actions, into: &buf)
        FfiConverterSequenceString.write(value.stateKeys, into: &buf)
        FfiConverterString.write(value.initialStateJson, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeModuleConfig_lift(_ buf: RustBuffer) throws -> ModuleConfig {
    return try FfiConverterTypeModuleConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeModuleConfig_lower(_ value: ModuleConfig) -> RustBuffer {
    return FfiConverterTypeModuleConfig.lower(value)
}


/**
 * A patch represents a single DOM operation
 */
public struct Patch {
    public var patchType: PatchType
    public var id: String
    public var elementType: String?
    public var propsJson: String?
    public var name: String?
    public var valueJson: String?
    public var text: String?
    public var parentId: String?
    public var beforeId: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(patchType: PatchType, id: String, elementType: String?, propsJson: String?, name: String?, valueJson: String?, text: String?, parentId: String?, beforeId: String?) {
        self.patchType = patchType
        self.id = id
        self.elementType = elementType
        self.propsJson = propsJson
        self.name = name
        self.valueJson = valueJson
        self.text = text
        self.parentId = parentId
        self.beforeId = beforeId
    }
}



extension Patch: Equatable, Hashable {
    public static func ==(lhs: Patch, rhs: Patch) -> Bool {
        if lhs.patchType != rhs.patchType {
            return false
        }
        if lhs.id != rhs.id {
            return false
        }
        if lhs.elementType != rhs.elementType {
            return false
        }
        if lhs.propsJson != rhs.propsJson {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.valueJson != rhs.valueJson {
            return false
        }
        if lhs.text != rhs.text {
            return false
        }
        if lhs.parentId != rhs.parentId {
            return false
        }
        if lhs.beforeId != rhs.beforeId {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(patchType)
        hasher.combine(id)
        hasher.combine(elementType)
        hasher.combine(propsJson)
        hasher.combine(name)
        hasher.combine(valueJson)
        hasher.combine(text)
        hasher.combine(parentId)
        hasher.combine(beforeId)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePatch: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Patch {
        return
            try Patch(
                patchType: FfiConverterTypePatchType.read(from: &buf), 
                id: FfiConverterString.read(from: &buf), 
                elementType: FfiConverterOptionString.read(from: &buf), 
                propsJson: FfiConverterOptionString.read(from: &buf), 
                name: FfiConverterOptionString.read(from: &buf), 
                valueJson: FfiConverterOptionString.read(from: &buf), 
                text: FfiConverterOptionString.read(from: &buf), 
                parentId: FfiConverterOptionString.read(from: &buf), 
                beforeId: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: Patch, into buf: inout [UInt8]) {
        FfiConverterTypePatchType.write(value.patchType, into: &buf)
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterOptionString.write(value.elementType, into: &buf)
        FfiConverterOptionString.write(value.propsJson, into: &buf)
        FfiConverterOptionString.write(value.name, into: &buf)
        FfiConverterOptionString.write(value.valueJson, into: &buf)
        FfiConverterOptionString.write(value.text, into: &buf)
        FfiConverterOptionString.write(value.parentId, into: &buf)
        FfiConverterOptionString.write(value.beforeId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePatch_lift(_ buf: RustBuffer) throws -> Patch {
    return try FfiConverterTypePatch.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePatch_lower(_ value: Patch) -> RustBuffer {
    return FfiConverterTypePatch.lower(value)
}


/**
 * Error type for engine operations
 */
public enum HypenError {

    
    
    case ParseError(String
    )
    case RenderError(String
    )
    case StateError(String
    )
    case ActionError(String
    )
    case ComponentError(String
    )
    case InitializationError(String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHypenError: FfiConverterRustBuffer {
    typealias SwiftType = HypenError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HypenError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .ParseError(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .RenderError(
            try FfiConverterString.read(from: &buf)
            )
        case 3: return .StateError(
            try FfiConverterString.read(from: &buf)
            )
        case 4: return .ActionError(
            try FfiConverterString.read(from: &buf)
            )
        case 5: return .ComponentError(
            try FfiConverterString.read(from: &buf)
            )
        case 6: return .InitializationError(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: HypenError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .ParseError(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .RenderError(v1):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .StateError(v1):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .ActionError(v1):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .ComponentError(v1):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .InitializationError(v1):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


extension HypenError: Equatable, Hashable {}

extension HypenError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Patch types for DOM operations
 */

public enum PatchType {
    
    case create
    case setProp
    case setText
    case insert
    case move
    case remove
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePatchType: FfiConverterRustBuffer {
    typealias SwiftType = PatchType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PatchType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .create
        
        case 2: return .setProp
        
        case 3: return .setText
        
        case 4: return .insert
        
        case 5: return .move
        
        case 6: return .remove
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PatchType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .create:
            writeInt(&buf, Int32(1))
        
        
        case .setProp:
            writeInt(&buf, Int32(2))
        
        
        case .setText:
            writeInt(&buf, Int32(3))
        
        
        case .insert:
            writeInt(&buf, Int32(4))
        
        
        case .move:
            writeInt(&buf, Int32(5))
        
        
        case .remove:
            writeInt(&buf, Int32(6))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePatchType_lift(_ buf: RustBuffer) throws -> PatchType {
    return try FfiConverterTypePatchType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePatchType_lower(_ value: PatchType) -> RustBuffer {
    return FfiConverterTypePatchType.lower(value)
}



extension PatchType: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAction: FfiConverterRustBuffer {
    typealias SwiftType = [Action]

    public static func write(_ value: [Action], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAction.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Action] {
        let len: Int32 = try readInt(&buf)
        var seq = [Action]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAction.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeImportInfo: FfiConverterRustBuffer {
    typealias SwiftType = [ImportInfo]

    public static func write(_ value: [ImportInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeImportInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ImportInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [ImportInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeImportInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypePatch: FfiConverterRustBuffer {
    typealias SwiftType = [Patch]

    public static func write(_ value: [Patch], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePatch.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Patch] {
        let len: Int32 = try readInt(&buf)
        var seq = [Patch]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypePatch.read(from: &buf))
        }
        return seq
    }
}
/**
 * Version information
 */
public func version() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_hypen_engine_fn_func_version($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_hypen_engine_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_hypen_engine_checksum_func_version() != 23507) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_clear_tree() != 10950) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_dispatch_action() != 45087) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_get_pending_actions() != 8901) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_get_pending_imports() != 41481) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_get_revision() != 44487) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_parse_to_json() != 29302) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_register_action() != 6397) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_register_component() != 12279) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_register_primitive() != 59275) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_render_source() != 53455) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_set_module() != 16247) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_update_state() != 59479) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_constructor_hypenengine_new() != 14615) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all