// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(hypen_engineFFI)
import hypen_engineFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_hypen_engine_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_hypen_engine_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureHypenEngineInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            throw CancellationError()

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * The main Hypen engine interface
 */
public protocol HypenEngineProtocol: AnyObject, Sendable {
    
    /**
     * Look up which named module owns an action.
     *
     * Returns `Some(module_name)` if the action was registered via
     * [`register_module`], or `None` if it belongs to the primary module
     * (via [`set_module`]) or isn't known to the engine. Hosts use this to
     * route follow-up `update_state` calls to the correct scope after
     * [`dispatch_action`].
     */
    func actionScopeFor(actionName: String)  -> String?
    
    /**
     * Clear the render tree
     */
    func clearTree() 
    
    /**
     * Dispatch an action (queued for polling)
     */
    func dispatchAction(actionName: String, payloadJson: String?) throws 
    
    /**
     * Return the list of standard Hypen primitive element names.
     */
    func getDefaultPrimitives()  -> [String]
    
    /**
     * Get pending actions (clears the queue)
     */
    func getPendingActions()  -> [Action]
    
    /**
     * Get pending imports from the last rendered document (clears the queue)
     * Call this after render_source() to discover which components need to be resolved.
     * For each import, use register_component() to provide the resolved component source.
     */
    func getPendingImports()  -> [ImportInfo]
    
    /**
     * Get the current revision number
     */
    func getRevision()  -> UInt64
    
    /**
     * Parse Hypen DSL and return AST as JSON
     */
    func parseToJson(source: String) throws  -> String
    
    /**
     * Register an action handler name
     */
    func registerAction(actionName: String) 
    
    /**
     * Register a component from source
     */
    func registerComponent(component: ComponentDef) throws 
    
    /**
     * Register all standard Hypen primitives (Text, Column, Row, Button, etc.)
     */
    func registerDefaultPrimitives() 
    
    /**
     * Register a named module for multi-module apps.
     * The engine scopes `${state.xxx}` bindings to this module's state
     * when rendering a component whose source starts with `module <name> { ... }`.
     */
    func registerModule(config: ModuleConfig) 
    
    /**
     * Register a primitive element type
     */
    func registerPrimitive(name: String) 
    
    /**
     * Register a single resource from raw SVG content.
     */
    func registerResource(name: String, svg: String) throws 
    
    /**
     * Register resources from a JSON object: `{ "heart": "<svg>...</svg>", "search": "<svg>...</svg>" }`.
     *
     * SDKs should prefer scanning directories themselves (via their native
     * filesystem APIs) and passing the resulting map through this method.
     * The engine owns SVG parsing; SDKs are dumb file-readers.
     */
    func registerResources(resourcesJson: String) throws 
    
    /**
     * Remove a data source context and re-render bound nodes.
     *
     * Mirrors WASI's `hypen_remove_context` and JS's `removeContext`: the
     * call auto-renders dirty nodes and returns any resulting patches.
     */
    func removeContext(name: String) throws  -> [Patch]
    
    /**
     * Render Hypen DSL source and return patches.
     *
     * Supports documents with `import` statements — call
     * [`get_pending_imports`](Self::get_pending_imports) afterwards to
     * retrieve imports the host SDK should resolve and re-feed via
     * [`register_component`](Self::register_component).
     */
    func renderSource(source: String) throws  -> [Patch]
    
    /**
     * Set (or replace) a named data source context and re-render bound nodes.
     *
     * # Arguments
     * * `name` — provider name (e.g. `"spacetime"`)
     * * `data_json` — JSON blob representing the entire provider state.
     * Passing a non-object is allowed; the engine stores the raw value.
     *
     * Mirrors WASI's `hypen_set_context` and JS's `setContext`: the call
     * auto-renders dirty nodes and returns any resulting patches.
     */
    func setContext(name: String, dataJson: String) throws  -> [Patch]
    
    /**
     * Set module configuration
     */
    func setModule(config: ModuleConfig) 
    
    /**
     * Update engine state with a JSON patch and re-render affected nodes.
     *
     * # Arguments
     * * `scope` — Empty string targets the primary module set via [`set_module`].
     * A non-empty value (e.g. `"search"`) targets a named module
     * registered via [`register_module`]; invalidation is scoped
     * to `mod:<scope>:<path>` so sibling modules are not re-rendered.
     * * `state_json` — JSON object with state changes (deep-merged into the
     * target module's state).
     */
    func updateState(scope: String, stateJson: String) throws  -> [Patch]
    
    /**
     * Apply a sparse state update with explicit dotted path → value pairs.
     *
     * Use this when you already know which paths changed (typical for the
     * `ObservableState`-driven mobile SDKs) so the engine doesn't need to
     * walk a nested patch to find them. Each path is applied directly to
     * the target module's state and used to invalidate dependencies.
     *
     * # Arguments
     * * `scope` — Empty string targets the primary module, otherwise the
     * named module registered via [`register_module`]. Case is
     * normalized internally.
     * * `paths_json` — JSON array of dotted path strings (`["count"]`,
     * `["user.name", "user.email"]`).
     * * `values_json` — JSON object keyed by the same paths.
     */
    func updateStateSparse(scope: String, pathsJson: String, valuesJson: String) throws  -> [Patch]
    
}
/**
 * The main Hypen engine interface
 */
open class HypenEngine: HypenEngineProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_hypen_engine_fn_clone_hypenengine(self.handle, $0) }
    }
    /**
     * Create a new engine instance
     */
public convenience init()throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeHypenError_lift) {
    uniffi_hypen_engine_fn_constructor_hypenengine_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_hypen_engine_fn_free_hypenengine(handle, $0) }
    }

    

    
    /**
     * Look up which named module owns an action.
     *
     * Returns `Some(module_name)` if the action was registered via
     * [`register_module`], or `None` if it belongs to the primary module
     * (via [`set_module`]) or isn't known to the engine. Hosts use this to
     * route follow-up `update_state` calls to the correct scope after
     * [`dispatch_action`].
     */
open func actionScopeFor(actionName: String) -> String?  {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
    uniffi_hypen_engine_fn_method_hypenengine_action_scope_for(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(actionName),$0
    )
})
}
    
    /**
     * Clear the render tree
     */
open func clearTree()  {try! rustCall() {
    uniffi_hypen_engine_fn_method_hypenengine_clear_tree(
            self.uniffiCloneHandle(),$0
    )
}
}
    
    /**
     * Dispatch an action (queued for polling)
     */
open func dispatchAction(actionName: String, payloadJson: String?)throws   {try rustCallWithError(FfiConverterTypeHypenError_lift) {
    uniffi_hypen_engine_fn_method_hypenengine_dispatch_action(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(actionName),
        FfiConverterOptionString.lower(payloadJson),$0
    )
}
}
    
    /**
     * Return the list of standard Hypen primitive element names.
     */
open func getDefaultPrimitives() -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_hypen_engine_fn_method_hypenengine_get_default_primitives(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Get pending actions (clears the queue)
     */
open func getPendingActions() -> [Action]  {
    return try!  FfiConverterSequenceTypeAction.lift(try! rustCall() {
    uniffi_hypen_engine_fn_method_hypenengine_get_pending_actions(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Get pending imports from the last rendered document (clears the queue)
     * Call this after render_source() to discover which components need to be resolved.
     * For each import, use register_component() to provide the resolved component source.
     */
open func getPendingImports() -> [ImportInfo]  {
    return try!  FfiConverterSequenceTypeImportInfo.lift(try! rustCall() {
    uniffi_hypen_engine_fn_method_hypenengine_get_pending_imports(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Get the current revision number
     */
open func getRevision() -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_hypen_engine_fn_method_hypenengine_get_revision(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Parse Hypen DSL and return AST as JSON
     */
open func parseToJson(source: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeHypenError_lift) {
    uniffi_hypen_engine_fn_method_hypenengine_parse_to_json(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(source),$0
    )
})
}
    
    /**
     * Register an action handler name
     */
open func registerAction(actionName: String)  {try! rustCall() {
    uniffi_hypen_engine_fn_method_hypenengine_register_action(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(actionName),$0
    )
}
}
    
    /**
     * Register a component from source
     */
open func registerComponent(component: ComponentDef)throws   {try rustCallWithError(FfiConverterTypeHypenError_lift) {
    uniffi_hypen_engine_fn_method_hypenengine_register_component(
            self.uniffiCloneHandle(),
        FfiConverterTypeComponentDef_lower(component),$0
    )
}
}
    
    /**
     * Register all standard Hypen primitives (Text, Column, Row, Button, etc.)
     */
open func registerDefaultPrimitives()  {try! rustCall() {
    uniffi_hypen_engine_fn_method_hypenengine_register_default_primitives(
            self.uniffiCloneHandle(),$0
    )
}
}
    
    /**
     * Register a named module for multi-module apps.
     * The engine scopes `${state.xxx}` bindings to this module's state
     * when rendering a component whose source starts with `module <name> { ... }`.
     */
open func registerModule(config: ModuleConfig)  {try! rustCall() {
    uniffi_hypen_engine_fn_method_hypenengine_register_module(
            self.uniffiCloneHandle(),
        FfiConverterTypeModuleConfig_lower(config),$0
    )
}
}
    
    /**
     * Register a primitive element type
     */
open func registerPrimitive(name: String)  {try! rustCall() {
    uniffi_hypen_engine_fn_method_hypenengine_register_primitive(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),$0
    )
}
}
    
    /**
     * Register a single resource from raw SVG content.
     */
open func registerResource(name: String, svg: String)throws   {try rustCallWithError(FfiConverterTypeHypenError_lift) {
    uniffi_hypen_engine_fn_method_hypenengine_register_resource(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),
        FfiConverterString.lower(svg),$0
    )
}
}
    
    /**
     * Register resources from a JSON object: `{ "heart": "<svg>...</svg>", "search": "<svg>...</svg>" }`.
     *
     * SDKs should prefer scanning directories themselves (via their native
     * filesystem APIs) and passing the resulting map through this method.
     * The engine owns SVG parsing; SDKs are dumb file-readers.
     */
open func registerResources(resourcesJson: String)throws   {try rustCallWithError(FfiConverterTypeHypenError_lift) {
    uniffi_hypen_engine_fn_method_hypenengine_register_resources(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(resourcesJson),$0
    )
}
}
    
    /**
     * Remove a data source context and re-render bound nodes.
     *
     * Mirrors WASI's `hypen_remove_context` and JS's `removeContext`: the
     * call auto-renders dirty nodes and returns any resulting patches.
     */
open func removeContext(name: String)throws  -> [Patch]  {
    return try  FfiConverterSequenceTypePatch.lift(try rustCallWithError(FfiConverterTypeHypenError_lift) {
    uniffi_hypen_engine_fn_method_hypenengine_remove_context(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),$0
    )
})
}
    
    /**
     * Render Hypen DSL source and return patches.
     *
     * Supports documents with `import` statements — call
     * [`get_pending_imports`](Self::get_pending_imports) afterwards to
     * retrieve imports the host SDK should resolve and re-feed via
     * [`register_component`](Self::register_component).
     */
open func renderSource(source: String)throws  -> [Patch]  {
    return try  FfiConverterSequenceTypePatch.lift(try rustCallWithError(FfiConverterTypeHypenError_lift) {
    uniffi_hypen_engine_fn_method_hypenengine_render_source(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(source),$0
    )
})
}
    
    /**
     * Set (or replace) a named data source context and re-render bound nodes.
     *
     * # Arguments
     * * `name` — provider name (e.g. `"spacetime"`)
     * * `data_json` — JSON blob representing the entire provider state.
     * Passing a non-object is allowed; the engine stores the raw value.
     *
     * Mirrors WASI's `hypen_set_context` and JS's `setContext`: the call
     * auto-renders dirty nodes and returns any resulting patches.
     */
open func setContext(name: String, dataJson: String)throws  -> [Patch]  {
    return try  FfiConverterSequenceTypePatch.lift(try rustCallWithError(FfiConverterTypeHypenError_lift) {
    uniffi_hypen_engine_fn_method_hypenengine_set_context(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),
        FfiConverterString.lower(dataJson),$0
    )
})
}
    
    /**
     * Set module configuration
     */
open func setModule(config: ModuleConfig)  {try! rustCall() {
    uniffi_hypen_engine_fn_method_hypenengine_set_module(
            self.uniffiCloneHandle(),
        FfiConverterTypeModuleConfig_lower(config),$0
    )
}
}
    
    /**
     * Update engine state with a JSON patch and re-render affected nodes.
     *
     * # Arguments
     * * `scope` — Empty string targets the primary module set via [`set_module`].
     * A non-empty value (e.g. `"search"`) targets a named module
     * registered via [`register_module`]; invalidation is scoped
     * to `mod:<scope>:<path>` so sibling modules are not re-rendered.
     * * `state_json` — JSON object with state changes (deep-merged into the
     * target module's state).
     */
open func updateState(scope: String, stateJson: String)throws  -> [Patch]  {
    return try  FfiConverterSequenceTypePatch.lift(try rustCallWithError(FfiConverterTypeHypenError_lift) {
    uniffi_hypen_engine_fn_method_hypenengine_update_state(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(scope),
        FfiConverterString.lower(stateJson),$0
    )
})
}
    
    /**
     * Apply a sparse state update with explicit dotted path → value pairs.
     *
     * Use this when you already know which paths changed (typical for the
     * `ObservableState`-driven mobile SDKs) so the engine doesn't need to
     * walk a nested patch to find them. Each path is applied directly to
     * the target module's state and used to invalidate dependencies.
     *
     * # Arguments
     * * `scope` — Empty string targets the primary module, otherwise the
     * named module registered via [`register_module`]. Case is
     * normalized internally.
     * * `paths_json` — JSON array of dotted path strings (`["count"]`,
     * `["user.name", "user.email"]`).
     * * `values_json` — JSON object keyed by the same paths.
     */
open func updateStateSparse(scope: String, pathsJson: String, valuesJson: String)throws  -> [Patch]  {
    return try  FfiConverterSequenceTypePatch.lift(try rustCallWithError(FfiConverterTypeHypenError_lift) {
    uniffi_hypen_engine_fn_method_hypenengine_update_state_sparse(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(scope),
        FfiConverterString.lower(pathsJson),
        FfiConverterString.lower(valuesJson),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHypenEngine: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = HypenEngine

    public static func lift(_ handle: UInt64) throws -> HypenEngine {
        return HypenEngine(unsafeFromHandle: handle)
    }

    public static func lower(_ value: HypenEngine) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HypenEngine {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: HypenEngine, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHypenEngine_lift(_ handle: UInt64) throws -> HypenEngine {
    return try FfiConverterTypeHypenEngine.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHypenEngine_lower(_ value: HypenEngine) -> UInt64 {
    return FfiConverterTypeHypenEngine.lower(value)
}




/**
 * Action dispatched from UI
 */
public struct Action: Equatable, Hashable {
    public var name: String
    public var payloadJson: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, payloadJson: String?) {
        self.name = name
        self.payloadJson = payloadJson
    }

    

    
}

#if compiler(>=6)
extension Action: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAction: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Action {
        return
            try Action(
                name: FfiConverterString.read(from: &buf), 
                payloadJson: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: Action, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterOptionString.write(value.payloadJson, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAction_lift(_ buf: RustBuffer) throws -> Action {
    return try FfiConverterTypeAction.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAction_lower(_ value: Action) -> RustBuffer {
    return FfiConverterTypeAction.lower(value)
}


/**
 * Component definition for registration
 */
public struct ComponentDef: Equatable, Hashable {
    public var name: String
    public var source: String
    public var path: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, source: String, path: String) {
        self.name = name
        self.source = source
        self.path = path
    }

    

    
}

#if compiler(>=6)
extension ComponentDef: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeComponentDef: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ComponentDef {
        return
            try ComponentDef(
                name: FfiConverterString.read(from: &buf), 
                source: FfiConverterString.read(from: &buf), 
                path: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ComponentDef, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.source, into: &buf)
        FfiConverterString.write(value.path, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeComponentDef_lift(_ buf: RustBuffer) throws -> ComponentDef {
    return try FfiConverterTypeComponentDef.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeComponentDef_lower(_ value: ComponentDef) -> RustBuffer {
    return FfiConverterTypeComponentDef.lower(value)
}


/**
 * Import information returned to SDK hosts (Kotlin, Swift, etc.)
 */
public struct ImportInfo: Equatable, Hashable {
    /**
     * Component names being imported (e.g., ["Button", "Card"])
     */
    public var names: [String]
    /**
     * Source path (e.g., "./components/ui" or "https://cdn.example.com/ui")
     */
    public var sourcePath: String
    /**
     * Source type: "local" or "url"
     */
    public var sourceType: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Component names being imported (e.g., ["Button", "Card"])
         */names: [String], 
        /**
         * Source path (e.g., "./components/ui" or "https://cdn.example.com/ui")
         */sourcePath: String, 
        /**
         * Source type: "local" or "url"
         */sourceType: String) {
        self.names = names
        self.sourcePath = sourcePath
        self.sourceType = sourceType
    }

    

    
}

#if compiler(>=6)
extension ImportInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeImportInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ImportInfo {
        return
            try ImportInfo(
                names: FfiConverterSequenceString.read(from: &buf), 
                sourcePath: FfiConverterString.read(from: &buf), 
                sourceType: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ImportInfo, into buf: inout [UInt8]) {
        FfiConverterSequenceString.write(value.names, into: &buf)
        FfiConverterString.write(value.sourcePath, into: &buf)
        FfiConverterString.write(value.sourceType, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImportInfo_lift(_ buf: RustBuffer) throws -> ImportInfo {
    return try FfiConverterTypeImportInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImportInfo_lower(_ value: ImportInfo) -> RustBuffer {
    return FfiConverterTypeImportInfo.lower(value)
}


/**
 * Module configuration
 */
public struct ModuleConfig: Equatable, Hashable {
    public var name: String
    public var actions: [String]
    public var stateKeys: [String]
    public var initialStateJson: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, actions: [String], stateKeys: [String], initialStateJson: String) {
        self.name = name
        self.actions = actions
        self.stateKeys = stateKeys
        self.initialStateJson = initialStateJson
    }

    

    
}

#if compiler(>=6)
extension ModuleConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeModuleConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ModuleConfig {
        return
            try ModuleConfig(
                name: FfiConverterString.read(from: &buf), 
                actions: FfiConverterSequenceString.read(from: &buf), 
                stateKeys: FfiConverterSequenceString.read(from: &buf), 
                initialStateJson: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ModuleConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterSequenceString.write(value.actions, into: &buf)
        FfiConverterSequenceString.write(value.stateKeys, into: &buf)
        FfiConverterString.write(value.initialStateJson, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeModuleConfig_lift(_ buf: RustBuffer) throws -> ModuleConfig {
    return try FfiConverterTypeModuleConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeModuleConfig_lower(_ value: ModuleConfig) -> RustBuffer {
    return FfiConverterTypeModuleConfig.lower(value)
}


/**
 * A patch represents a single DOM operation
 */
public struct Patch: Equatable, Hashable {
    public var patchType: PatchType
    public var id: String
    public var elementType: String?
    public var propsJson: String?
    public var name: String?
    public var valueJson: String?
    public var text: String?
    public var parentId: String?
    public var beforeId: String?
    /**
     * Serialized `Semantics` block (camelCase JSON, same shape as the web
     * wire format). Present on `Create` for nodes with derivable a11y and
     * on every `SetSemantics`. Defaults to `None` so existing Kotlin/Swift
     * constructors keep compiling.
     */
    public var semanticsJson: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(patchType: PatchType, id: String, elementType: String?, propsJson: String?, name: String?, valueJson: String?, text: String?, parentId: String?, beforeId: String?, 
        /**
         * Serialized `Semantics` block (camelCase JSON, same shape as the web
         * wire format). Present on `Create` for nodes with derivable a11y and
         * on every `SetSemantics`. Defaults to `None` so existing Kotlin/Swift
         * constructors keep compiling.
         */semanticsJson: String? = nil) {
        self.patchType = patchType
        self.id = id
        self.elementType = elementType
        self.propsJson = propsJson
        self.name = name
        self.valueJson = valueJson
        self.text = text
        self.parentId = parentId
        self.beforeId = beforeId
        self.semanticsJson = semanticsJson
    }

    

    
}

#if compiler(>=6)
extension Patch: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePatch: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Patch {
        return
            try Patch(
                patchType: FfiConverterTypePatchType.read(from: &buf), 
                id: FfiConverterString.read(from: &buf), 
                elementType: FfiConverterOptionString.read(from: &buf), 
                propsJson: FfiConverterOptionString.read(from: &buf), 
                name: FfiConverterOptionString.read(from: &buf), 
                valueJson: FfiConverterOptionString.read(from: &buf), 
                text: FfiConverterOptionString.read(from: &buf), 
                parentId: FfiConverterOptionString.read(from: &buf), 
                beforeId: FfiConverterOptionString.read(from: &buf), 
                semanticsJson: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: Patch, into buf: inout [UInt8]) {
        FfiConverterTypePatchType.write(value.patchType, into: &buf)
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterOptionString.write(value.elementType, into: &buf)
        FfiConverterOptionString.write(value.propsJson, into: &buf)
        FfiConverterOptionString.write(value.name, into: &buf)
        FfiConverterOptionString.write(value.valueJson, into: &buf)
        FfiConverterOptionString.write(value.text, into: &buf)
        FfiConverterOptionString.write(value.parentId, into: &buf)
        FfiConverterOptionString.write(value.beforeId, into: &buf)
        FfiConverterOptionString.write(value.semanticsJson, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePatch_lift(_ buf: RustBuffer) throws -> Patch {
    return try FfiConverterTypePatch.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePatch_lower(_ value: Patch) -> RustBuffer {
    return FfiConverterTypePatch.lower(value)
}


/**
 * Error type for engine operations
 */
public enum HypenError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case ParseError(String
    )
    case RenderError(String
    )
    case StateError(String
    )
    case ActionError(String
    )
    case ComponentError(String
    )
    case InitializationError(String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension HypenError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHypenError: FfiConverterRustBuffer {
    typealias SwiftType = HypenError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HypenError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .ParseError(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .RenderError(
            try FfiConverterString.read(from: &buf)
            )
        case 3: return .StateError(
            try FfiConverterString.read(from: &buf)
            )
        case 4: return .ActionError(
            try FfiConverterString.read(from: &buf)
            )
        case 5: return .ComponentError(
            try FfiConverterString.read(from: &buf)
            )
        case 6: return .InitializationError(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: HypenError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .ParseError(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .RenderError(v1):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .StateError(v1):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .ActionError(v1):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .ComponentError(v1):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .InitializationError(v1):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHypenError_lift(_ buf: RustBuffer) throws -> HypenError {
    return try FfiConverterTypeHypenError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHypenError_lower(_ value: HypenError) -> RustBuffer {
    return FfiConverterTypeHypenError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Patch types for DOM operations
 */

public enum PatchType: Equatable, Hashable {
    
    case create
    case setProp
    case removeProp
    case setText
    case insert
    case move
    case remove
    /**
     * Unlink a subtree from its parent without destroying it. Renderer
     * keeps the native element alive for a later `Attach`. Emitted by
     * the engine's Router subtree cache on navigation-away.
     */
    case detach
    /**
     * Reattach a previously-detached subtree under the same NodeId.
     * Emitted by the engine's Router subtree cache on navigation-back.
     */
    case attach
    /**
     * Replace a node's accessibility semantics after a reactive change
     * (templated accessible name, bound self-state, bound checked). The
     * updated block rides `semantics_json`; renderers re-apply it with the
     * same translation they run at create, clearing attributes the new
     * block no longer sets. `semantics_json == None` clears everything.
     */
    case setSemantics





}

#if compiler(>=6)
extension PatchType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePatchType: FfiConverterRustBuffer {
    typealias SwiftType = PatchType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PatchType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .create
        
        case 2: return .setProp
        
        case 3: return .removeProp
        
        case 4: return .setText
        
        case 5: return .insert
        
        case 6: return .move
        
        case 7: return .remove
        
        case 8: return .detach
        
        case 9: return .attach
        
        case 10: return .setSemantics
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PatchType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .create:
            writeInt(&buf, Int32(1))
        
        
        case .setProp:
            writeInt(&buf, Int32(2))
        
        
        case .removeProp:
            writeInt(&buf, Int32(3))
        
        
        case .setText:
            writeInt(&buf, Int32(4))
        
        
        case .insert:
            writeInt(&buf, Int32(5))
        
        
        case .move:
            writeInt(&buf, Int32(6))
        
        
        case .remove:
            writeInt(&buf, Int32(7))
        
        
        case .detach:
            writeInt(&buf, Int32(8))
        
        
        case .attach:
            writeInt(&buf, Int32(9))
        
        
        case .setSemantics:
            writeInt(&buf, Int32(10))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePatchType_lift(_ buf: RustBuffer) throws -> PatchType {
    return try FfiConverterTypePatchType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePatchType_lower(_ value: PatchType) -> RustBuffer {
    return FfiConverterTypePatchType.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAction: FfiConverterRustBuffer {
    typealias SwiftType = [Action]

    public static func write(_ value: [Action], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAction.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Action] {
        let len: Int32 = try readInt(&buf)
        var seq = [Action]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAction.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeImportInfo: FfiConverterRustBuffer {
    typealias SwiftType = [ImportInfo]

    public static func write(_ value: [ImportInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeImportInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ImportInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [ImportInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeImportInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypePatch: FfiConverterRustBuffer {
    typealias SwiftType = [Patch]

    public static func write(_ value: [Patch], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePatch.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Patch] {
        let len: Int32 = try readInt(&buf)
        var seq = [Patch]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypePatch.read(from: &buf))
        }
        return seq
    }
}
/**
 * Match a URL pattern against a path.
 *
 * Returns a JSON string `{"matched": bool, "params": {"id": "42"}}`
 * on success. Unmatched patterns return `{"matched": false, "params": {}}`.
 * Replaces per-host `matchPath` ports.
 * Parse a Hypen DSL source and return every `Router { Route ... }` block
 * it contains. Returns JSON matching the TS / Go `discoverRouters`
 * shape — `[{ "module_scope": null|"name", "routes": [{ "path": "...",
 * "element_names": ["..."] }] }]`. The Swift/Kotlin SDKs use this to
 * auto-wire a per-session ManagedRouter so examples don't have to
 * repeat the route table in host code.
 */
public func discoverRouters(source: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeHypenError_lift) {
    uniffi_hypen_engine_fn_func_discover_routers(
        FfiConverterString.lower(source),$0
    )
})
}
/**
 * Build a URL from `path` and a JSON object of query params.
 */
public func portableBuildUrl(path: String, queryJson: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeHypenError_lift) {
    uniffi_hypen_engine_fn_func_portable_build_url(
        FfiConverterString.lower(path),
        FfiConverterString.lower(queryJson),$0
    )
})
}
/**
 * Decode a percent-encoded string; `+` decodes to space.
 */
public func portableDecodeUriComponent(input: String) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_hypen_engine_fn_func_portable_decode_uri_component(
        FfiConverterString.lower(input),$0
    )
})
}
/**
 * Compute the dotted-path diff between two JSON blobs.
 *
 * Accepts `old_json` and `new_json` as JSON strings; returns a JSON
 * array of `{"path": "...", "value": <json>}` objects describing every
 * leaf that changed. Replaces per-host `diffState` ports.
 */
public func portableDiffPaths(oldJson: String, newJson: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeHypenError_lift) {
    uniffi_hypen_engine_fn_func_portable_diff_paths(
        FfiConverterString.lower(oldJson),
        FfiConverterString.lower(newJson),$0
    )
})
}
/**
 * Percent-encode a string for use in URL query components.
 */
public func portableEncodeUriComponent(input: String) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_hypen_engine_fn_func_portable_encode_uri_component(
        FfiConverterString.lower(input),$0
    )
})
}
public func portableMatchPath(pattern: String, path: String) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_hypen_engine_fn_func_portable_match_path(
        FfiConverterString.lower(pattern),
        FfiConverterString.lower(path),$0
    )
})
}
/**
 * Split `"/path?k=v"` into JSON `{"path": "...", "query": {"k": "v"}}`.
 */
public func portableParseQuery(fullPath: String) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_hypen_engine_fn_func_portable_parse_query(
        FfiConverterString.lower(fullPath),$0
    )
})
}
/**
 * Delete the value at `path`. Returns `{"json": <updated>, "removed": bool}`.
 */
public func portablePathDelete(valueJson: String, path: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeHypenError_lift) {
    uniffi_hypen_engine_fn_func_portable_path_delete(
        FfiConverterString.lower(valueJson),
        FfiConverterString.lower(path),$0
    )
})
}
/**
 * Read the value at a dotted path; returns JSON (or `"null"` if the
 * path doesn't resolve).
 */
public func portablePathGet(valueJson: String, path: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeHypenError_lift) {
    uniffi_hypen_engine_fn_func_portable_path_get(
        FfiConverterString.lower(valueJson),
        FfiConverterString.lower(path),$0
    )
})
}
/**
 * Returns `"true"` or `"false"` (JSON booleans) for whether `path`
 * resolves inside `value_json`.
 */
public func portablePathHas(valueJson: String, path: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeHypenError_lift) {
    uniffi_hypen_engine_fn_func_portable_path_has(
        FfiConverterString.lower(valueJson),
        FfiConverterString.lower(path),$0
    )
})
}
/**
 * Set `new_value_json` at `path` inside `value_json`; returns the
 * updated JSON. Intermediate objects are created; arrays are extended
 * with `null` padding.
 */
public func portablePathSet(valueJson: String, path: String, newValueJson: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeHypenError_lift) {
    uniffi_hypen_engine_fn_func_portable_path_set(
        FfiConverterString.lower(valueJson),
        FfiConverterString.lower(path),
        FfiConverterString.lower(newValueJson),$0
    )
})
}
/**
 * Advance the session state machine by one event.
 *
 * `state_json` and `event_json` are the serialised `SessionState` /
 * `SessionEvent` from the portable module. Returns the serialised
 * `SessionEffect`.
 */
public func portableSessionStep(stateJson: String, eventJson: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeHypenError_lift) {
    uniffi_hypen_engine_fn_func_portable_session_step(
        FfiConverterString.lower(stateJson),
        FfiConverterString.lower(eventJson),$0
    )
})
}
/**
 * Version information
 */
public func version() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_hypen_engine_fn_func_version($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_hypen_engine_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_hypen_engine_checksum_func_discover_routers() != 21914) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_func_portable_build_url() != 22763) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_func_portable_decode_uri_component() != 50262) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_func_portable_diff_paths() != 60546) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_func_portable_encode_uri_component() != 862) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_func_portable_match_path() != 41040) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_func_portable_parse_query() != 30856) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_func_portable_path_delete() != 14518) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_func_portable_path_get() != 31544) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_func_portable_path_has() != 26095) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_func_portable_path_set() != 30972) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_func_portable_session_step() != 5521) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_func_version() != 40847) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_action_scope_for() != 30596) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_clear_tree() != 26593) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_dispatch_action() != 61576) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_get_default_primitives() != 51381) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_get_pending_actions() != 3272) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_get_pending_imports() != 20508) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_get_revision() != 37374) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_parse_to_json() != 19998) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_register_action() != 39860) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_register_component() != 63523) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_register_default_primitives() != 60158) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_register_module() != 24227) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_register_primitive() != 34549) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_register_resource() != 59265) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_register_resources() != 42808) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_remove_context() != 59104) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_render_source() != 47301) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_set_context() != 49927) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_set_module() != 9330) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_update_state() != 65422) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_method_hypenengine_update_state_sparse() != 14668) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hypen_engine_checksum_constructor_hypenengine_new() != 42970) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureHypenEngineInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all