/**
 * Build script to generate component imports
 * Reads .hypen files and generates TypeScript files with embedded templates
 * Supports import statements in .hypen files
 */

import { readdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

const componentsDir = "./src/components";

/**
 * Parse import statements from Hypen DSL text
 */
function parseImports(text: string): Array<{ names: string[]; source: string }> {
  const imports: Array<{ names: string[]; source: string }> = [];
  const importRegex = /import\s+(?:\{([^}]+)\}|(\w+))\s+from\s+["']([^"']+)["']/g;

  let match;
  while ((match = importRegex.exec(text)) !== null) {
    const [, namedImports, defaultImport, source] = match;

    let names: string[];
    if (namedImports) {
      // Named imports: { Button, Card }
      names = namedImports
        .split(",")
        .map((n) => n.trim())
        .filter((n) => n.length > 0);
    } else {
      // Default import: HomePage
      names = [defaultImport];
    }

    imports.push({ names, source });
  }

  return imports;
}

/**
 * Remove import statements from Hypen template
 * Import statements should not be part of the template
 */
function removeImports(text: string): string {
  return text.replace(/import\s+(?:\{[^}]+\}|\w+)\s+from\s+["'][^"']+["']\s*/g, '');
}

async function generateComponentImports() {
  const { existsSync } = await import("fs");
  const components = readdirSync(componentsDir, { withFileTypes: true })
    .filter((dirent) => dirent.isDirectory())
    .map((dirent) => dirent.name);

  let output = `/**
 * Auto-generated component imports
 * Generated by build-components.ts
 */\n\n`;

  // Track all imports across components
  const allImports = new Set<string>();

  for (const componentName of components) {
    const hypenPath = join(componentsDir, componentName, "component.hypen");
    const tsPath = join(componentsDir, componentName, "component.ts");

    try {
      // Check if .hypen file exists
      if (!existsSync(hypenPath)) {
        console.log(`⏭️  Skipping ${componentName}: no component.hypen file`);
        continue;
      }

      const templateRaw = readFileSync(hypenPath, "utf-8");

      // Parse and remove imports from template
      const imports = parseImports(templateRaw);
      const template = removeImports(templateRaw);
      const templateEscaped = JSON.stringify(template);

      // Track imports for later processing
      if (imports.length > 0) {
        console.log(`📦 Found ${imports.length} import(s) in ${componentName}`);
        for (const imp of imports) {
          console.log(`   - ${imp.names.join(", ")} from "${imp.source}"`);
          // For now, we just log them. In a full implementation,
          // we'd resolve these imports and include them in the generated output
          allImports.add(imp.source);
        }
      }

      // Check if .ts file exists - if not, create a stateless component
      if (existsSync(tsPath)) {
        // Module (stateful) - import the .ts file
        const relativeImport = `./components/${componentName}/component.js`;
        output += `// ${componentName} (module - stateful)\n`;
        output += `import ${componentName}Module from "${relativeImport}";
export const ${componentName} = {
  module: ${componentName}Module,
  template: ${templateEscaped},
};\n\n`;
        console.log(`✓ Loaded ${componentName} (module - stateful)`);
      } else {
        // Component (stateless) - no .ts file needed
        output += `// ${componentName} (component - stateless)\n`;
        output += `import { app } from "@hypen-space/core";
const ${componentName}Module = app.defineState({}).build();
export const ${componentName} = {
  module: ${componentName}Module,
  template: ${templateEscaped},
};\n\n`;
        console.log(`✓ Loaded ${componentName} (component - stateless)`);
      }
    } catch (error) {
      console.error(`✗ Failed to load ${componentName}:`, error);
    }
  }

  writeFileSync("./src/components.generated.ts", output);
  console.log("✅ Generated component imports");
}

generateComponentImports();
