import { RemoteEngine } from "../../hypen-web/packages/core/src/remote/client.ts";
import { DOMRenderer, CanvasRenderer } from "../../hypen-web/packages/web/src/index.ts";
import { WebDeviceHost } from "../../hypen-web/packages/device-web/src/index.ts";
const params = new URLSearchParams(location.search);
const port = params.get("port") ?? "45101";
const select = document.querySelector<HTMLSelectElement>("#server")!;
select.value = port;
select.onchange = () => { params.set("port", select.value); location.search = params.toString(); };
const url = `ws://127.0.0.1:${port}/ws?token=device-lab`;
const engine = new RemoteEngine(url, { device: new WebDeviceHost({ origin: new URL(url).origin }), autoReconnect: true });
const root = document.querySelector<HTMLDivElement>("#app")!;
const canvas = document.createElement("canvas");
if (params.get("renderer") === "canvas") root.append(canvas);
const renderer = params.get("renderer") === "canvas" ? new CanvasRenderer(canvas, engine) : new DOMRenderer(root, engine);
engine.onPatches(patches => renderer.applyPatches(patches));
engine.onSessionEstablished(info => { document.querySelector("#connection")!.textContent = "Connected · " + info.sessionId.slice(0,8); });
engine.onDisconnect(() => { document.querySelector("#connection")!.textContent = "Disconnected"; });
engine.onError(error => { document.querySelector("#connection")!.textContent = String(error); });
void engine.connect();
